### ISSUE TITLE
string is empty if app is not running

### ISSUE THREAD

**Issue by MatzeOGH** [TROPHiT/UnityDeeplinks#1] opened 2016-09-30 20:16 UTC
Hi,
First of all thanks for the plugin.
But we have a problem with the Plugin.
If our app is not running and the deep link starts the app the deeplink method does not get called by the activity.
Is there any way of fixing this issue?

We are using the GoogleVR plugin and we want to keep the UI that comes with the plugin

`<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:icon="@drawable/app_icon"
                 android:label="@string/app_name">

```
    <activity android:name="com.trophit.DeeplinkActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="stereosense" />
      </intent-filter>
    </activity>

    <activity android:name="com.google.unity.GoogleUnityActivity"
              android:label="@string/app_name"
              android:screenOrientation="portrait"
              android:launchMode="singleTask"
              android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <category android:name="com.google.intent.category.CARDBOARD" />
        </intent-filter>
        <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>

    <meta-data android:name="IMMERSIVE_MODE" android:value="true" />
</application>
<!-- Set target sdk version to Lollipop to prevent issues with Marshmallow's runtime permissions. -->
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="22" />
<uses-feature android:glEsVersion="0x00020000" />
<uses-feature android:name="android.hardware.sensor.accelerometer" android:required="true"/>
<uses-feature android:name="android.hardware.sensor.gyroscope" android:required="true"/>
<uses-permission android:name="android.permission.NFC"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.INTERNET" />

<!-- VR feature tags. -->
<uses-feature android:name="android.software.vr.mode" android:required="false"/>
<uses-feature android:name="android.hardware.vr.high_performance" android:required="false"/>
```

</manifest>
`

**Comment by sagimann** [comment] 2016-10-13 12:31
The reason for this is that when the app isn't running and is restarted via the second activity, the Unity native libs are not yet initialized. I'm able to reproduce this. Alternative #1 seems to be the solution, as if the invoked activity is the Unity player itself, it takes care of lib initialization. I'm now updating this module's instructions to converge on alternative #1 rather than #2.

**Comment by xtiandiaz** [comment] 2017-04-06 12:11
Hi, first off thanks very much for your code, it has helped me greatly so far. 
I want to follow up the same issue started above, for I can also reproduce it after following the latest Android setup guide, using the latest version of the code. so, the deep links are received nicely by our app whilst it's running. However if the deep link launched the app in the first place, the Unity message won't be sent.
Currently we have it configured so that our Player Activity class extends from Unity Player Activity, and we're referencing this custom one from the Manifest.
@sagimann I coudn't get what's the alternative #1 you refered to previously.
Thanks in advance!

**Comment by TROPHiT** [comment] 2017-04-11 13:28
Hi, I am unable to reproduce your symptom. Can you please confirm that you have not only referenced your custom activity in the manifest as the main activity, but also added the URL intent filter to that same activity?

**Comment by xtiandiaz** [comment] 2017-04-12 08:57
Hi, thanks for your reply. So here's what I have in the manifest:
```
...
<activity android:name="com.myapp.MyAppPlayerActivity" android:label="@string/app_name" android:screenOrientation="sensorLandscape" android:launchMode="singleInstance" android:hardwareAccelerated="true" android:resizeableActivity="false">
  <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="myapp" />
  </intent-filter>
  <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
    <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
  </intent-filter>
  <!-- intent-filter ${applicationId}.MESSAGE here allows to start Activity directly from push notification without restarting whole application -->
  <intent-filter>
    <action android:name="com.myapp.myapp.MESSAGE" />
    <category android:name="android.intent.category.DEFAULT" />
  </intent-filter>
  <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
  <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
</activity>
...
```
There are as well other activities such as:
```
...  
<activity android:name="com.prime31.GoogleIABProxyActivity" android:configChanges="orientation" />
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
<meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="true" />
<activity android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
<activity android:name="com.facebook.LoginActivity" android:configChanges="keyboardHidden|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
<activity android:name="com.facebook.unity.FBUnityGameRequestActivity" />
<activity android:name="com.facebook.unity.FBUnityCreateGameGroupActivity" />
<activity android:name="com.facebook.unity.FBUnityJoinGameGroupActivity" />
<activity android:name="com.facebook.unity.AppInviteDialogActivity" />
<activity android:name="com.facebook.unity.LikeDialogActivity" android:exported="true">
...
```
But none of them are marked as default (?). And for the sake of explicitness, deep-linking works fine on Android, but only if the app is already running in background. If the deep-link launches the app, it is not "remembered" in my current setup. Thanks for any help!

**Comment by TROPHiT** [comment] 2017-04-12 17:21
1. com.myapp.MyAppPlayerActivity extends from the unity player activity, correct?
2. did you merge the given code from the repo's activity into yours? It would help to see some debug messages in order to understand which methods are being activated in the "bad" test case..

**Comment by xtiandiaz** [comment] 2017-04-12 18:43
@TROPHiT 
1. yes.
2. and yes. I can enable the debug messages and paste here the result. Unfortunately I won't have access to an Android device within the next few days, I'll do as soon as possible.

**Comment by TROPHiT** [comment] 2017-04-14 07:44
Sounds good, I'll await the update

**Comment by xtiandiaz** [comment] 2017-04-19 11:25
@TROPHiT So I got `"onDeepLink " + deepLink` logged on the console when launching the app from a deep link. It looks like the message is correctly sent to Unity, but our game object isn't yet ready to receive it. A probable cause is that the game object isn't in the Scene in the first place, but is later instantiated from the `Start` of a global initializer. 
We do this to prevent regular changes to the scenes, often leading to versioning conflicts. I will find a workaround in the app, otherwise is it possible to delay the message delivery as it intrinsically happens on iOS?

**Comment by TROPHiT** [comment] 2017-04-19 11:47
Try pushing the deeplink init script down the execution order. For example, if the game object as default execution order, set the deeplink script after all default executions.

**Comment by xtiandiaz** [comment] 2017-04-19 20:21
Thanks, that's a viable approach. Meanwhile I can corroborate that the deep linking takes place on launch when the listener gameObject is embedded into the scene 🎉

**Comment by TROPHiT** [comment] 2017-04-20 05:34
excellent, should the issue be considered closed?

**Comment by xtiandiaz** [comment] 2017-04-27 10:05
@TROPHiT Sorry for the late reply, and yes! 
Thanks again for your help.

**Closed** 2017-04-27 10:51 UTC
